# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 21:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True, max_length=420)),
                ('cover', models.ImageField(blank=True, upload_to=b'images')),
                ('likes', models.IntegerField(default=0)),
                ('visibility', models.CharField(choices=[(b'P', b'public'), (b'M', b'private'), (b'F', b'friends')], default=b'M', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(upload_to=b'images')),
                ('title', models.CharField(max_length=20)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wah.Album')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('bio', models.TextField(blank=True, max_length=420)),
                ('photo', models.ImageField(blank=True, upload_to=b'avatars')),
                ('password', models.CharField(blank=True, max_length=20)),
                ('confirm', models.CharField(blank=True, max_length=20)),
                ('friends', models.ManyToManyField(blank=True, related_name='friends', to=settings.AUTH_USER_MODEL)),
                ('pending_friends', models.ManyToManyField(blank=True, related_name='pending_friends', to=settings.AUTH_USER_MODEL)),
                ('profile_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='liked_people',
            field=models.ManyToManyField(to='wah.Profile'),
        ),
        migrations.AddField(
            model_name='album',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
