# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-20 02:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wah', '0003_auto_20161104_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
