# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-20 03:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wah', '0004_album_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='liked_people',
            field=models.ManyToManyField(to='wah.Profile'),
        ),
    ]
