# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-20 21:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wah', '0005_album_liked_people'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='visibility',
            field=models.CharField(choices=[(b'P', b'public'), (b'M', b'private'), (b'F', b'friends')], default=b'M', max_length=1),
        ),
    ]
